# Generated by Django 5.2.17 on 2026-09-30 21:39

from django.db import migrations, models


def banned_to_suspended(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(status="banned").update(status="suspended")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_status'),
    ]

    operations = [
        # Reversing leaves rows suspended: a former ban can't be told apart once merged.
        migrations.RunPython(banned_to_suspended, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20),
        ),
    ]
