# Generated by Django 5.2.17 on 2026-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_ref',
            field=models.CharField(blank=True, help_text='Stripe Checkout session id.', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('expired', 'Expired')], max_length=20),
        ),
    ]
