# Generated by Django 5.2.17 on 2026-10-10 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_order_receipt_url_expired_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When the order was refunded in full.', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_by',
            field=models.ForeignKey(blank=True, help_text='Blank for a refund made in Stripe or an automatic one.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunded_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
